--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Theslowaja/XGTShowPlayerHP
build-by-default: true
branches:
- master
projects:
  XGTShowPlayerHP:
    path: ""
    icon: "xgt.gif"
...
